name: NetHunter Kernel Builder (Garnet)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bc bison build-essential curl flex git \
          kmod libssl-dev libncurses5-dev libelf-dev \
          ccache dwarves zip unzip

    - name: Clone Proton Clang
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang.git clang

    - name: Export Environment Variables
      run: |
        echo "CLANG_PATH=$GITHUB_WORKSPACE/clang" >> $GITHUB_ENV
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "SUBARCH=arm64" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/clang/bin:$PATH" >> $GITHUB_ENV
        echo "KBUILD_COMPILER_STRING=$($GITHUB_WORKSPACE/clang/bin/clang --version | head -n 1)" >> $GITHUB_ENV

    - name: Kernel Defconfig
      run: |
        make O=out ARCH=$ARCH SUBARCH=$SUBARCH garnet_defconfig

    - name: Compile Kernel
      run: |
        make -j$(nproc) O=out ARCH=$ARCH SUBARCH=$SUBARCH \
          CC=clang \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
          CLANG_TRIPLE=aarch64-linux-gnu-

    - name: Check Kernel Image
      run: |
        if [ ! -f out/arch/arm64/boot/Image.gz-dtb ]; then
          echo "❌ Build failed: Image.gz-dtb not found"
          exit 1
        fi
        echo "✅ Kernel built successfully"

    - name: Clone AnyKernel3 (NetHunter)
      run: |
        git clone --depth=1 https://github.com/offensive-security/nethunter-kernel-builder.git anykernel

    - name: Prepare Flashable ZIP
      run: |
        cp out/arch/arm64/boot/Image.gz-dtb anykernel/
        cd anykernel
        zip -r9 ../NetHunter_Garnet_Kernel.zip *

    - name: Upload Kernel ZIP
      uses: actions/upload-artifact@v4
      with:
        name: NetHunter-Kernel-Garnet
        path: NetHunter_Garnet_Kernel.zipp
